# Generated by Django 5.0.4 on 2024-05-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="seats",
            field=models.IntegerField(default=40),
        ),
        migrations.CreateModel(
            name="historicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicalData",
                        to="SchoolApp.childmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.FloatField()),
                ("mathematics", models.FloatField()),
                ("chemistry", models.FloatField()),
                ("biology", models.FloatField()),
                ("history", models.FloatField()),
                ("geography", models.FloatField()),
                ("politics", models.FloatField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject",
                        to="SchoolApp.childmodel",
                    ),
                ),
            ],
        ),
    ]
