# Generated by Django 5.0.4 on 2024-04-12 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SchoolApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Child",
            new_name="ChildModel",
        ),
        migrations.RenameModel(
            old_name="Class",
            new_name="ClassModel",
        ),
        migrations.RenameModel(
            old_name="Enroll",
            new_name="EnrollModel",
        ),
        migrations.RenameModel(
            old_name="Parent",
            new_name="ParentModel",
        ),
    ]
